### ISSUE TITLE
Stable Release Fall 2018 TODO List

### ISSUE THREAD

**Issue by akohlmey** [lammps/lammps#1213]
The purpose of this issue is to keep track of (manual) testing and release engineering tasks for the next stable release, currently planned for early December 2018.

In addition to the regular automated tests here are additional tests and checks to be performed:
- [x] review recent/open defects reported by Coverity Scan
- [x] run all example and test inputs with valgrind's memcheck
- [x] run all example inputs with GNU GCC's sanitizer (asan,ubsan,tsan)
- [ ] run a variety of inputs with GPU package enabled using both OpenCL and CUDA and check for segfaults and memory leaks
- [ ] rerun and update all example and benchmark log outputs
- [x] spell-check the manual
- [x] white-space cleanup (tabs to spaces, remove trailing spaces) for C++ sources and manual sources
- [ ] visually review documentation output (html and pdf) and fix formatting issues
- [x] validate all library targets requiring a download, update versions and/or checksums where needed
- [x] prepare release summary describing major changes since the last stable release
- [ ] test MPICH against OpenMPI on selected systems
- [x] check if newer version binaries for bundled tools in windows installer packages exist and update if needed
- [ ] review which (new) packages/libs/settings can be included into windows packages
- [ ] test if KOKKOS/OpenMP can be included in cross-compilation windows build

Test conventional build on several systems:
- [ ] Linux clang
- [x] Linux gcc 8.x (Fedora 29)
- [ ] Linux gcc 4.4 (RHEL 6.x)
- [x] Linux gcc 4.8 (RHEL 7.x)
- [ ] Linux Intel compiler (2018)
- [x] Windows 32-bit (via MinGW cross compiler)
- [x] Windows 64-bit (via MinGW cross compiler)

Test CMake build on several systems:
- [x] Linux clang
- [x] Linux gcc 8.x (Fedora 29)
- [ ] Linux gcc 4.4 (RHEL 6.x)
- [x] Linux gcc 4.8 (RHEL 7.x)
- [x] Linux gcc 4.8 (Ubuntu 14.04)
- [ ] Linux Intel compiler (2018)
- [ ] Windows 32-bit (via MinGW cross compiler)
- [ ] Windows 64-bit (via MinGW cross compiler)

**Comment by akohlmey** [comment]
Enough done for this one.
