### ISSUE TITLE
Stable Release TODO list

### ISSUE THREAD

**Issue by akohlmey** [lammps/lammps#4229]
Known issues:
- [x] KOKKOS version of pair style uf3 is incomplete. Needs to be removed if not corrected.
---
Compile LAMMPS with -fsanitize=<style> and run examples:
- [x] address
- [ ] leak
- [ ] thread (with OpenMP)
- [ ] undefined
---
- [ ] get new (partial) regression testing up-and-running with GitHub actions
---
- [ ] Compile LAMMPS with floating point traps enabled and trapping integer overflows and run examples:
---
- [ ] Compile LAMMPS with -Og and debug info and run all examples with valgrind
- [x] Same as above and run `ctest -T memcheck` (need to disable death tests to reduce false positives)
---
- [x] Compile with -Wvla and try to eliminate flagged variable length arrays
---
- [x] compile with IWYU (aka include-what-you-use) to detect  unused and missing include statements
--- 
- [ ]  apply clang-format
---
- [x] review and potentially fix recently reported issues from static code analysis with Coverity scan
---
- [x] check compilation on FreeBSD
- [x] check compilation on Debian
- [x] check compilation on Solaris (via OpenIndiana)
- [x] test macOS installer
- [x] test flatpak installer
- [ ] test Windows installer
---
- [x] visually inspect HTML manual
- [x] visually inspect PDF manual
- [x] update Bibliography (extract citations from doc packages, sort and compare/update with existing file)
---
- [ ] update versionadded/versionchanged/deprecated tags to release date
- [ ] set release version and remove update entry from version.h
- [ ] update flatpak build xml file to use the release branch

**Comment by evoyiatzis** [comment]
Pages 128 & 129 in https://docs.lammps.org/Manual.pdf
There is an extra blank line in the tables listing the bond angle dihedral and improper potentials.
Also in page 127 there are some empty cells in the third row of the table for the pair potentials (not sure if it is intentional)

**Comment by akohlmey** [comment]
> There is an extra blank line in the tables listing the bond angle dihedral and improper potentials.
> Also in page 127 there are some empty cells in the third row of the table for the pair potentials (not sure if it is intentional)

All of these are intentional. There is supposed to be a separation between "special"  styles like hybrid and the conventional styles. In the case of pair styles, actually an extra empty row needs to be added since the addition of the "hybrid/molecular" pair style.

It looks better with HTML...

**Comment by evoyiatzis** [comment]
Page 2318 in the pdf it seems there is some info missing for the pair styles

**Comment by alphataubio** [comment]
> Compile LAMMPS with -fsanitize=<style> and run examples:

maybe this can automated with GoogleTest [ [https://google.github.io/googletest/advanced.html](https://google.github.io/googletest/advanced.html) ] ? but it would be only for the unit tests not the regression examples.

>Sanitizer Integration
The [Undefined Behavior Sanitizer](https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html), [Address Sanitizer](https://github.com/google/sanitizers/wiki/AddressSanitizer), and [Thread Sanitizer](https://github.com/google/sanitizers/wiki/ThreadSanitizerCppManual) all provide weak functions that you can override to trigger explicit failures when they detect sanitizer errors, such as creating a reference from nullptr. To override these functions, place definitions for them in a source file that you compile as part of your main binary:
```
extern "C" {
void __ubsan_on_report() {
  FAIL() << "Encountered an undefined behavior sanitizer error";
}
void __asan_on_error() {
  FAIL() << "Encountered an address sanitizer error";
}
void __tsan_on_report() {
  FAIL() << "Encountered a thread sanitizer error";
}
}  // extern "C"
```
>After compiling your project with one of the sanitizers enabled, if a particular test triggers a sanitizer error, GoogleTest will report that it failed.

**Comment by akohlmey** [comment]
> maybe this can automated with GoogleTest [ https://google.github.io/googletest/advanced.html ] ? but it would be only for the unit tests not the regression examples.

Not interested.
