### ISSUE TITLE
Further cmake improvements

### ISSUE THREAD

**Issue by junghans** [lammps/lammps#616]
From the call today, after #573 is merged, we should:
- [x] Copy Package Categories from Make system
- [x] `USER-MISC` doesn't depend on `MANYBODY`, but can use it
- [x] Check `PYTHON` relationship with `BUILD_SHARED_LIBS`(update: dependency removed)
- [x] Download and build `Voro++` using `ExternalProject_Add()` (#902)
- [x] Make sure `src/` is last include directory (RB: might no longer be needed) (#623)
- [x] Remove auto-generated `style_*.h` in `src/` at cmake time (#623)
- [x] Exclude package `cpp` files (`src/*/*.cpp`) from `LIB_SOURCE` to make cmake usable with release tarball (#623)
- [x] Build `lib` package as static (optionally shared) lib instead of objects. (#627)
- [x] Add option to add suffix to `liblammps` and `lmp` (#625)
- [x] Make sure `kokkos` can not be enabled  together with other accelerator packages (RB: outdated, not necessary according to Stan)
- [x] Documentation
- [x] Print `CXXFLAGS` at the end of cmake (#626)
- [x] Ensure intel package gets compiled with `icc` and inject `-ffast` flags (#910)
- [x] OpenCL support in GPU pacakge
- [x] Install potential files
- [x] Install `lammps.sh` /` lammps.csh` ?
- [ ] CPack support for Windows package?
- [x] Add FindLAMMPS.cmake (#1086)
- [x] Add USER-MESO build

**Comment by junghans** [comment]
> Make sure src/ is last include directory (RB: might no longer be needed)

When deleting all `style_*.h` (as in #623) we should be good.

**Comment by stanmoore1** [comment]
>Make sure kokkos can not be enabled together with other accelerator packages

The USER-CUDA (deprecated) and KOKKOS packages were incompatible, but as far as I know there are no issues with building kokkos with the USER-OMP or GPU packages. I need to modify the docs.

**Comment by rbberger** [comment]
Started working on a more detailed doc page some time ago, pushed it as updated README.md on this branch here https://github.com/rbberger/lammps/tree/cmake_documentation/cmake. Haven't decided on the final file format though. The goal is to get every possible configuration option documented, add examples for special configurations and showcase common workflows.

**Comment by akohlmey** [comment]
Question: cmake doesn't allow enabling POEMS and BODY at the same time. is there a file name conflict? or something else?

**Comment by junghans** [comment]
@akohlmey 

> Question: cmake doesn't allow enabling POEMS and BODY at the same time. is there a file name conflict? or something else?

When we added CMake, there was a compile error when enabling both, but I cannot reproduce that anymore, so let's remove that conflict message.

**Comment by junghans** [comment]
To-Do list from meeting yesterday:
- [ ] Improve summary
  - Add MPI flags
  - Add CPPFLAGS
  - Add CMake's feature summary
- [ ] Stricter checking against make-based build system - Advice user to run `make no-all purge`
- [ ] Document pkg-config feature
- [ ] Add options for
  - JPEG
  - PNG
  - FFMPEG
 - GZIP
- [ ] Improve KSPACE package build
  - Add option for precision of fft
  - Prefer FFTW3 over KISSFT if found by CMake.
  - Remove FFTW2 support
- [ ] Check for `zlib` when building `COMPRESS`
- [ ] Add "is experimental` warning of `QMMM`
- [ ] Drop `-fno-second-underscore` stuff
- [ ] NetCDF: Check hard-coded defines
- [ ] LATTE: add option to download instead of doing it automatically
- [ ] VORO: add download option
- [ ] SMD: add option to download Eigen3
- [ ] USER-INTEL
  - Require `icc` (with developer overwrite)
  - Inject @wmbrownIntel flags
- [ ] Add `BUILD_OMP` option (default ON if compiler supports it)
- [ ] Add `BUILD_MPI` option ((default ON if MPI found)
- [ ] GPU
  - make `GPU_ARCH` more similar to KOKKOS
  - print out summary

**Comment by junghans** [comment]
@akohlmey, when dropping `-fno-second-underscore`, `MEAM` doesn't compile with:
```
libmeam.a(meam_dens_final.F.o): In function `dg_gam_':
meam_dens_final.F:(.text+0x1c3): undefined reference to `fm_exp_'
meam_dens_final.F:(.text+0x213): undefined reference to `fm_exp_'
libmeam.a(meam_dens_final.F.o): In function `g_gam_':
meam_dens_final.F:(.text+0x3aa): undefined reference to `fm_exp_'
libmeam.a(meam_dens_init.F.o): In function `calc_rho1_':
meam_dens_init.F:(.text+0x498): undefined reference to `fm_exp_'
meam_dens_init.F:(.text+0x4eb): undefined reference to `fm_exp_'
libmeam.a(meam_dens_init.F.o):meam_dens_init.F:(.text+0x533): more undefined references to `fm_exp_' follow
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/lmp.dir/build.make:103: lmp] Error 1
make[1]: *** [CMakeFiles/Makefile2:146: CMakeFiles/lmp.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by akohlmey** [comment]
@junghans i don't think it has anything to do with `-fno-second-underscore`. Please check whether you compiled `fm_exp.c` which is a C(!) file that needs to be compiled and included in libmeam.a

**Comment by junghans** [comment]
You are right, the *C* file triggered it!

**Comment by sjplimp** [comment]
@junghans this list from out meeting looks complete to me - thanks!

**Comment by akohlmey** [comment]
@junghans @rbberger this looks a bit confusing now. i suggest to close this issue and open a new one listing only remaining issues.

**Comment by junghans** [comment]
Sure, @rbberger will meet in two weeks and look through the remaining CMake issues.

**Comment by junghans** [comment]
FindLammps.cmake is done in #1086, CPack support for Windows package will be done later.
